# Generated by Django 4.2.5 on 2024-11-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('link', models.TextField()),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.TextField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movieuser')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
