# Generated by Django 4.2.5 on 2024-11-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
