# Generated by Django 4.2.5 on 2024-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movieuser_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieuser',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
