# Generated by Django 4.2.5 on 2024-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movieuser_id_alter_movieuser_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieuser',
            name='type',
        ),
    ]
