# Generated by Django 4.2.5 on 2024-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_movieuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuser',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
